ALTER TABLE "users"
  ADD COLUMN IF NOT EXISTS "first_name" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "last_name"  VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "phone"      VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "dpi"        VARCHAR(30);
